### ISSUE TITLE
Identify the dataset for training and testing the model

### ISSUE THREAD

**Issue by jennyrrrrr** [XuweiyiChen/Pedestrian_vehicles#2]
- street view from drive's visual
- urban environment with pedestrians and vehicles.

**Comment by XuweiyiChen** [comment]
We first utilized the Caltech datasets, but there are far more backgrounds than frames with actual pedestrians. Then we turned ourselves into PASCAL VOC and COCO datasets. 

Both of the datasets include urban environments with pedestriansa and vehicles.
